// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFTGCuiwT8IYOk6sgj0fnbUr9T4OIHgfo',
    appId: '1:505516791211:web:ce319d1c4f71786f3e2eee',
    messagingSenderId: '505516791211',
    projectId: 'pcs-8-8835d',
    authDomain: 'pcs-8-8835d.firebaseapp.com',
    storageBucket: 'pcs-8-8835d.firebasestorage.app',
    measurementId: 'G-E79E2M03RC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe4djQ0NwdAi4RFx_NNnWL-48FQwVmQuE',
    appId: '1:505516791211:android:75de50d9f6c14a1f3e2eee',
    messagingSenderId: '505516791211',
    projectId: 'pcs-8-8835d',
    storageBucket: 'pcs-8-8835d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0R-_IpPNI7UoUVazFc5hzbUDpxI08a2s',
    appId: '1:505516791211:ios:d5c24a01d7d0a7563e2eee',
    messagingSenderId: '505516791211',
    projectId: 'pcs-8-8835d',
    storageBucket: 'pcs-8-8835d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0R-_IpPNI7UoUVazFc5hzbUDpxI08a2s',
    appId: '1:505516791211:ios:d5c24a01d7d0a7563e2eee',
    messagingSenderId: '505516791211',
    projectId: 'pcs-8-8835d',
    storageBucket: 'pcs-8-8835d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFTGCuiwT8IYOk6sgj0fnbUr9T4OIHgfo',
    appId: '1:505516791211:web:5646a4f7ce18b7933e2eee',
    messagingSenderId: '505516791211',
    projectId: 'pcs-8-8835d',
    authDomain: 'pcs-8-8835d.firebaseapp.com',
    storageBucket: 'pcs-8-8835d.firebasestorage.app',
    measurementId: 'G-EK6EE2D0CW',
  );
}
